#!/usr/bin/env bash

actual_checksum=$(curl http://terminus.org/packages/phar/terminus.phar | md5sum | cut -d ' ' -f 1)

echo "expected:" $(curl -s http://terminus.org/packages/phar/terminus.phar.md5)
echo "actual:  " $actual_checksum
